### ISSUE TITLE
图片识别报错，请教这是什么问题

### ISSUE THREAD

**Issue by GoalBlinkcn** [chungkwong/MathOCR#5]
十月 08, 2018 8:47:00 下午 com.github.chungkwong.mathocr.character.ModelManager getCharacterList
严重: null
java.nio.file.NoSuchFileException: C:\Users\Administrator\.mathocr\default_small\index
	at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
	at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(Unknown Source)
	at java.nio.file.Files.newByteChannel(Unknown Source)
	at java.nio.file.Files.newByteChannel(Unknown Source)
	at java.nio.file.spi.FileSystemProvider.newInputStream(Unknown Source)
	at java.nio.file.Files.newInputStream(Unknown Source)
	at java.nio.file.Files.newBufferedReader(Unknown Source)
	at java.nio.file.Files.lines(Unknown Source)
	at java.nio.file.Files.lines(Unknown Source)
	at com.github.chungkwong.mathocr.character.CharacterList.read(CharacterList.java:67)
	at com.github.chungkwong.mathocr.character.ModelManager.getCharacterList(ModelManager.java:38)
	at com.github.chungkwong.mathocr.character.ModelManager.loadDefault(ModelManager.java:78)
	at com.github.chungkwong.mathocr.character.ModelManager.getCharacterList(ModelManager.java:33)
	at com.github.chungkwong.mathocr.text.SptialCharacterSegmenter.segment(SptialCharacterSegmenter.java:34)
	at com.github.chungkwong.mathocr.text.BuiltinLineRecognizer.recognize(BuiltinLineRecognizer.java:31)
	at com.github.chungkwong.mathocr.PipeLine.recognizeLatexFormula(PipeLine.java:238)
	at com.github.chungkwong.mathocr.ui.MathInspector.inspect(MathInspector.java:44)
	at com.github.chungkwong.mathocr.ui.MathInspector.lambda$new$0(MathInspector.java:38)
	at javax.swing.JFileChooser.fireActionPerformed(Unknown Source)
	at javax.swing.JFileChooser.approveSelection(Unknown Source)
	at javax.swing.plaf.basic.BasicFileChooserUI$Handler.mouseClicked(Unknown Source)
	at sun.swing.FilePane$Handler.mouseClicked(Unknown Source)
	at java.awt.AWTEventMulticaster.mouseClicked(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

十月 08, 2018 8:47:00 下午 com.github.chungkwong.mathocr.character.ModelManager getModel
严重: null
java.io.FileNotFoundException: C:\Users\Administrator\.mathocr\default_small\LINEAR (系统找不到指定的路径。)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(Unknown Source)
	at java.io.FileInputStream.<init>(Unknown Source)
	at de.bwaldvogel.liblinear.Linear.loadModel(Linear.java:451)
	at com.github.chungkwong.mathocr.character.classifier.LinearModelType.read(LinearModelType.java:80)
	at com.github.chungkwong.mathocr.character.classifier.LinearModelType.read(LinearModelType.java:32)
	at com.github.chungkwong.mathocr.character.ModelManager.getModel(ModelManager.java:98)
	at com.github.chungkwong.mathocr.character.ModelManager.getSmallModel(ModelManager.java:87)
	at com.github.chungkwong.mathocr.text.SptialCharacterSegmenter.segment(SptialCharacterSegmenter.java:37)
	at com.github.chungkwong.mathocr.text.BuiltinLineRecognizer.recognize(BuiltinLineRecognizer.java:31)
	at com.github.chungkwong.mathocr.PipeLine.recognizeLatexFormula(PipeLine.java:238)
	at com.github.chungkwong.mathocr.ui.MathInspector.inspect(MathInspector.java:44)
	at com.github.chungkwong.mathocr.ui.MathInspector.lambda$new$0(MathInspector.java:38)
	at javax.swing.JFileChooser.fireActionPerformed(Unknown Source)
	at javax.swing.JFileChooser.approveSelection(Unknown Source)
	at javax.swing.plaf.basic.BasicFileChooserUI$Handler.mouseClicked(Unknown Source)
	at sun.swing.FilePane$Handler.mouseClicked(Unknown Source)
	at java.awt.AWTEventMulticaster.mouseClicked(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at com.github.chungkwong.mathocr.character.classifier.LinearClassifier.recognize(LinearClassifier.java:43)
	at com.github.chungkwong.mathocr.text.SptialCharacterSegmenter.segment(SptialCharacterSegmenter.java:46)
	at com.github.chungkwong.mathocr.text.BuiltinLineRecognizer.recognize(BuiltinLineRecognizer.java:31)
	at com.github.chungkwong.mathocr.PipeLine.recognizeLatexFormula(PipeLine.java:238)
	at com.github.chungkwong.mathocr.ui.MathInspector.inspect(MathInspector.java:44)
	at com.github.chungkwong.mathocr.ui.MathInspector.lambda$new$0(MathInspector.java:38)
	at javax.swing.JFileChooser.fireActionPerformed(Unknown Source)
	at javax.swing.JFileChooser.approveSelection(Unknown Source)
	at javax.swing.plaf.basic.BasicFileChooserUI$Handler.mouseClicked(Unknown Source)
	at sun.swing.FilePane$Handler.mouseClicked(Unknown Source)
	at java.awt.AWTEventMulticaster.mouseClicked(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by chungkwong** [comment]
阁下报告的问题应该已经在最新的版本（提交#957dac63167ad473dc619aba4cdacb5dece7f343，已同步到Maven仓库）中修复。由于MathOCR在首次运行时会把默认的模型文件复制到用户目录下再使用以便用户定制自己的模型，而本人之前地疏忽把复制路径打错了，导致找不到模型的情况。而实验用的机器中模型早已在预期的地方，导致未能及时发现这个问题，谨此致歉。感谢阁下对MathOCR项目的支持。

**Comment by GoalBlinkcn** [comment]
> 阁下报告的问题应该已经在最新的版本（提交#957dac63167ad473dc619aba4cdacb5dece7f343，已同步到Maven仓库）中修复。由于MathOCR在首次运行时会把默认的模型文件复制到用户目录下再使用以便用户定制自己的模型，而本人之前地疏忽把复制路径打错了，导致找不到模型的情况。而实验用的机器中模型早已在预期的地方，导致未能及时发现这个问题，谨此致歉。感谢阁下对MathOCR项目的支持。

好的，感谢。最近在用mathpix，识别率比较高，但是不能批量而且不识别中文。

**Comment by chungkwong** [comment]
> > 阁下报告的问题应该已经在最新的版本（提交#957dac63167ad473dc619aba4cdacb5dece7f343，已同步到Maven仓库）中修复。由于MathOCR在首次运行时会把默认的模型文件复制到用户目录下再使用以便用户定制自己的模型，而本人之前地疏忽把复制路径打错了，导致找不到模型的情况。而实验用的机器中模型早已在预期的地方，导致未能及时发现这个问题，谨此致歉。感谢阁下对MathOCR项目的支持。
> 
> 好的，感谢。最近在用mathpix，识别率比较高，但是不能批量而且不识别中文。

mathpix 有API（参见https://mathpix.com/api.html ），可以批量调用，与其它OCR的接口相比收费也不算太贵。至于中文，虽然默认MathOCR没有提供中文已训练模型，但已经提供了用中文字体训练的方法，感觉上效果和十年前的商用OCR软件差不多。
